- name: 'Install SCL repository'
  yum:
    name: centos-release-scl-rh
    state: present

- name: 'Install NodeJS SCL'
  yum:
    name:
      - "{{ nodejs_scl_version }}-npm"
    state: present

- name: Enable and configure SCL at login
  blockinfile:
    dest: /etc/profile.d/enable-{{ nodejs_scl_version }}.sh
    create: yes
    block: |
      #!/bin/bash
      source scl_source enable {{ nodejs_scl_version }}
