# Role:
# jenkins-user-add
#
# Objective:
#
# This role's sole objective is to properly setup the `jenkins` user on a 
# new OS environment to be used with Pulp QE Jenkins.
#
# All Key information is maintained within an encrypted ansible-vault.
#
# Default user variable information is maintained in the `defaults/`
# directory. 
---
- name: Include jenkins variable information
  include_vars: 
    file: vars/jenkins.yaml
    name: jenkins

- name: Create the {{ ci_user }} group
  group:
      name: "{{ ci_user }}"
      state: present
  become: yes

- name: Create the {{ ci_user }} User
  user:
      name: "{{ ci_user }}"
      comment: Jenkins CI user
      group: "{{ ci_user }}"
      password: "{{ jenkins.ci_password }}"
  become: yes

- name: Create symbolic link for jenkins agent to user home
  file:
    src: /home/{{ ci_user }}/
    dest: /var/lib/jenkins
    state: link
    force: yes

- name: Create {{ ci_user }} .ssh directory 
  file:
    path: /home/{{ ci_user }}/.ssh/
    state: directory
    mode: 0700
    group: "{{ ci_user }}"
    owner: "{{ ci_user }}"
    recurse: yes
  become: yes

- name: Create {{ ci_user }} User Authorized Keys
  file:
    path: /home/{{ ci_user }}/.ssh/authorized_keys
    state: touch
    mode: 0600
    group: "{{ ci_user }}"
    owner: "{{ ci_user }}"
  become: yes

- name: Set jenkins key in authorized_keys
  lineinfile:
    dest: /home/{{ci_user}}/.ssh/authorized_keys
    line: "{{ jenkins.public_key }}"
    state: present
  become: yes

- name: Create pulpadmin private key for rsync with fedorapeople.com
  file:
    path: /home/{{ ci_user }}/.ssh/id_rsa
    state: touch
    mode: 0600
    group: "{{ ci_user }}"
    owner: "{{ ci_user }}"
  become: yes

- name: Set pulpadmin key in id_rsa
  lineinfile:
    dest: /home/{{ci_user}}/.ssh/id_rsa
    line: "{{ jenkins.private_key }}"
    state: present
  become: yes

- name: Set includedir in sudoers
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"
  become: yes

- name: Add user {{ ci_user }} to sudo
  lineinfile:
    path: /etc/sudoers.d/{{ ci_user }}
    line: '{{ ci_user }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'
  become: yes
