## sudo apt-get update 
## sudo apt-get install openjdk-11-jdk -y 

## wget https://referenceapplicationskhaja.s3.us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar  -o /usr/share/spc/spring-petclinic.jar


sudo useradd spc
sudo password spc
sudo chown spc:spc /usr/share/spc/spring-petclinic.jar
sudo chmod 500 /usr/share/spc/spring-petclinic.jar


## /etc/systemd/system/spc.service

