---

- hosts: all
  vars:
    skip_restore_test: false
  roles:
    - role: subscription-manager
      when: ansible_distribution == 'RedHat'
    - role: pulp
    - role: lazy
      when: pulp_version is version('2.8', '>=')
    - role: pulp-certs
    - role: pulp-crane
    - role: pulp-restore-backup
    - role: pulp-test-populate
      when: not skip_restore_test

# This playbook runs roles to install pulp on a host, then restore previously
# backed up data.
#
# It expects that the data is in the from that the pulp_backup.yaml
# playbook delivers. See `local_bkup_dir` below.
#
# Example invocation:
#
# ansible-playbook -i ~/hosts -l rhel7 pulp_restore.yaml \
#                   -e local_bkup_dir=${HOME}/backups \
#                   -e remote_bkup_dir=/root/backups \
#                   -e rhn_password=my_pass \
#                   -e 'rhn_pool=my_pool' \
#                   -e rhn_username=my_username \
#                   -e pulp_build='stable' \
#                   -e pulp_version=2.13' \
#                   -e test_results_dir='/root'
#
# This would install 2.13 on the rhel7 host in your hosts file, and
# restore the backups found in ${HOME}/backups to the rhel7 host.
# Then it would run tests to report on the status of the restore
# and produce an xml report found in /root on the pulp host.
#
# Variables you might want to specify on invocation:
#
# local_bkup_dir: [absolute path on control node] default "local_backups"
#    This should point to a directory that, by default, has the following
#    contents, as is produced by the pulp-backup role.
#
#    local_bkup_dir/
#               ├── etc_pki_pulp.tar.bz2 # archive of /etc/pki/pulp/
#               ├── etc_pulp.tar.bz2     # archive of /etc/pulp/
#               ├── mongodb_backup.bz2   # archive of mongodump of pulp_database
#               └── var_lib_pulp.tar.bz2 # archive of /var/lib/pulp
#
#    If you would like to
#    provide your own archives, you can edit the files_to_restore dictionary
#    in "roles/pulp-restore-backup/defaults/main.yaml"
#
# remote_bkup_dir: [absolute path on pulp host] default:
#           "{{ ansible_user_dir }}/remote_backups"
#   This will create a directory on the remote host or use an existing
#   directory if one is provided in which to place the archives before they
#   are restored.
#
# skip_restore_test: [boolean] default FALSE
#   By default, this playbook tests that the content created by pulp-populate
#   role is present and functional. You should set this to TRUE if you did not
#   use the test data used by pulp-populate.
#
# test_results_dir: [absolute path on pulp host]
#   This is the directory in which the test results will be placed if running
#   restore tests. This is passed as an argument to
#   'roles/pulp-restore-backup/files/test_restore.sh'
#   This is not used if the restore tests are skipped.
