---
- name: Start Pulp
  service: "name={{ item }} state=started"
  loop:
    - httpd
    - pulp_celerybeat
    - pulp_resource_manager
    - pulp_streamer
    - pulp_workers
    - qpidd

- name: Install packages required for population task
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  loop:
    - python34
    - python34-setuptools
    - gcc
    - git

- name: Create a directory for virtualenvs
  file:
    path: "{{ ansible_user_dir }}/.venvs"
    state: directory

- name: Create a virtualenv
  command: python3 -m venv "{{ ansible_user_dir }}/.venvs/pulp-migrate"
  args:
    creates: "{{ ansible_user_dir }}/.venvs/pulp-migrate"
  register: result

# We fetch a zip with https://, because something asks for a password when this
# is used: git+https://git@github.com/PulpQE/pulp-migrate.git#egg=pulp-migrate
- name: Install pytest and pulp-migrate into the virtualenv
  shell: >
    source "{{ ansible_user_dir }}/.venvs/pulp-migrate/bin/activate" &&
    pip install pytest https://github.com/PulpQE/pulp-migrate/archive/master.zip#egg=pulp-migrate
  when: result is changed

- name: Create directory for pulp smash configuration file
  file:
    path: "{{ ansible_user_dir }}/.config/pulp_smash"
    state: directory

- name: Create pulp smash configuration file
  template:
    src: settings.j2
    dest: "{{ ansible_user_dir }}/.config/pulp_smash/settings.json"
