---
- name: 'Install GPG package'
  package:
    name: 'gpg'
    state: present
  tags:
    - packages
  when: ansible_distribution_release == "buster"

- name: 'Install Foreman GPG key'
  apt_key:
    url: https://deb.theforeman.org/foreman.asc

- name: 'Install Foreman {{ foreman_repositories_version }} repository'
  apt_repository:
    repo: deb http://deb.theforeman.org {{ ansible_distribution_release }} {{ foreman_repositories_version }}
    state: present

- name: 'Manage Foreman {{ foreman_repositories_version }} plugins repository'
  apt_repository:
    repo: deb http://deb.theforeman.org plugins {{ foreman_repositories_version }}
    state: "{{ foreman_repositories_plugins | ternary('present', 'absent') }}"
