---
- name: 'Remove foreman-release'
  yum:
    name: foreman-release
    state: absent
  tags:
    - packages

- name: 'Create module_hotfixes config file'
  copy:
    dest: /etc/yum/foreman.conf
    content: |
      module_hotfixes=1

- name: 'Foreman {{ foreman_repositories_version }} Koji repository'
  yum_repository:
    name: foreman-koji
    description: "Foreman {{ foreman_repositories_version }} Koji Repository"
    baseurl: "http://koji.katello.org/releases/yum/foreman-{{ foreman_repositories_version }}/RHEL/{{ ansible_distribution_major_version }}/x86_64/"
    priority: "1"
    gpgcheck: "0"
    include: /etc/yum/foreman.conf
  tags:
    - packages

- name: 'Foreman {{ foreman_repositories_version }} Plugins Koji repository'
  yum_repository:
    name: foreman-plugins-koji
    state: "{{ foreman_repositories_plugins | ternary('present', 'absent') }}"
    description: "Foreman Plugins {{ foreman_repositories_version }} Koji Repository"
    baseurl: "http://koji.katello.org/releases/yum/foreman-plugins-{{ foreman_repositories_version }}/RHEL/{{ ansible_distribution_major_version }}/x86_64/"
    priority: "1"
    gpgcheck: "0"
    include: /etc/yum/foreman.conf
  tags:
    - packages

- name: 'Foreman {{ foreman_repositories_version }} Rails SCL repository'
  yum_repository:
    name: foreman-rails
    description: "Rails SCL for Foreman {{ foreman_repositories_version }}"
    baseurl: "https://yum.theforeman.org/rails/foreman-{{ foreman_repositories_version }}/el{{ ansible_distribution_major_version }}/x86_64/"
    priority: "1"
    gpgcheck: "0"
  tags:
    - packages
  when:
    - foreman_repositories_version != "nightly"
    - foreman_repositories_version is version('1.24', '<=')
