---
- name: 'Setup Foreman {{ foreman_repositories_version }} Repository'
  yum:
    name: https://yum.theforeman.org/releases/{{ foreman_repositories_version }}/el{{ ansible_distribution_major_version }}/x86_64/foreman-release.rpm
    disable_gpg_check: True
    state: present
  tags:
    - packages
