name: Clean spam
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Run the spam cleaner
        shell: bash
        env:
          REDMINE_PASSWORD: ${{ secrets.REDMINE_PASSWORD }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          GOOGLE_CLIENT_CONFIG: ${{ secrets.GOOGLE_CLIENT_CONFIG }}
        run: |
          echo ::group::dependencies
          pip install dynaconf google_spreadsheet google-auth-oauthlib pandas selenium python-redmine tldextract
          echo ::endgroup::
          python .github/spam_cleaner.py
