koji-target-prefix: pulp-2.10
rsync-target-dir: 2.10/stage
rsync-tested-dir: 2.10/dev
repositories:
  - name: pulp
    external_deps: deps/external_deps.json
    git_url: git@github.com:pulp/pulp.git
    parent_branch: 2.10-dev
    git_branch: pulp-2.10.3-0.2.beta
    version: 2.10.3-1
  - name: pulp_puppet
    git_url: git@github.com:pulp/pulp_puppet.git
    parent_branch: 2.10-dev
    # the 2.10.3 beta 1 tag for puppet didn't get created, but
    # there were no changes since 2.10.2, so we can use that tag instead
    git_branch: pulp-puppet-2.10.2-1
    version: 2.10.3-1
  - name: pulp_rpm
    git_url: git@github.com:pulp/pulp_rpm.git
    # same problem as puppet, no tag. The current tip of 2.10-dev is the 2.10.4 alpha
    # version bump, which I made immedately after releasing beta 1. This is no fun. :(
    git_branch: 2.10-dev
    version: 2.10.3-1
  - name: pulp_docker
    git_url: git@github.com:pulp/pulp_docker.git
    git_branch: 2.1-release
    version: 2.1.0-1
  - name: crane
    git_url: git@github.com:pulp/crane.git
    git_branch: 2.0-release
    version: 2.0.2-1
  - name: pulp_ostree
    git_url: git@github.com:pulp/pulp_ostree.git
    git_branch: 1.1-release
    version: 1.1.4-1
  - name: pulp_python
    git_url: git@github.com:pulp/pulp_python.git
    git_branch: 1.1-release
    version: 1.1.3-1
