koji-target-prefix: pulp-2.13
rsync-target-dir: 2.13/stage
rsync-tested-dir: 2.13/dev
repositories:
  - name: pulp
    external_deps: deps/external_deps.json
    git_url: git@github.com:pulp/pulp.git
    git_branch: 2.13-release
    version: 2.13.4-1
  - name: pulp_puppet
    git_url: git@github.com:pulp/pulp_puppet.git
    git_branch: 2.13-release
    version: 2.13.4-1
  - name: pulp_rpm
    git_url: git@github.com:pulp/pulp_rpm.git
    git_branch: 2.13-release
    version: 2.13.4-1
  - name: pulp_docker
    git_url: git@github.com:pulp/pulp_docker.git
    git_branch: 2.4-release
    version: 2.4.1-2
  - name: crane
    git_url: git@github.com:pulp/crane.git
    git_branch: 2.1-release
    version: 2.1.0-1
  - name: pulp_ostree
    git_url: git@github.com:pulp/pulp_ostree.git
    git_branch: 1.2-release
    version: 1.2.1-3
  - name: pulp_python
    git_url: git@github.com:pulp/pulp_python.git
    git_branch: 2.0-release
    version: 2.0.0-2
