---

- name: Restart Apache service
  service:
    name: httpd
    state: restarted

- name: Restart Pulp workers service
  service:
    name: pulp_workers
    state: restarted

- name: Restart Pulp celerybeat service
  service:
    name: pulp_celerybeat
    state: restarted

- name: Restart Pulp resource manager service
  service:
    name: pulp_resource_manager
    state: restarted

- name: Restart goferd service
  service:
    name: goferd
    state: restarted

- name: Save IPv4 iptables configuration
  shell: 'iptables-save > /etc/sysconfig/iptables'

- name: Restart qpidd service
  service:
    name: qpidd
    state: restarted
