---
# tasks file for gameoflife
  - fail:
      msg: "try to perform this task on ubuntu"
    when: 
    - ansible_os_family != "Debian"
  - debug:
      msg: "initilizting the task"
  - name: "installing software-properties"
    apt:
      name: software-properties-common
      state: present
  - debug:
      msg: "installing java as a pre-requirement"
  - name: "install java8"
    apt: 
      name: default-jdk
      update_cache: yes
      state: present
  - name: "replacing environment file"
    file:    
      path: /etc/environment
      state: absent
  - name: "updating environment file"
    copy: 
      src: copy/environment
      dest: /etc/environment
  - name: "copying content to bashrc"
    copy:
      content: 'export JAVA_HOME=/usr/lib/jvm/java-8-oracle/jre
                export PATH=$JAVA_HOME/bin:$PATH'
      dest: ~/.bashrc
  - name: "refresh bashrc"
    shell: source ~/.bashrc
    args:
      executable: /bin/bash
  - debug: 
      msg: "Downloading and installing tomcat"
  - name: "adding tomcat group"
    group:
      name: tomcat
      state: present
  - name: "adding user tomcat"
    user:
      name: tomcat
      shell: /bin/false
      groups: tomcat
      append: yes
  - name: "downloading tomcat9"
    get_url:
      url: https://www-us.apache.org/dist/tomcat/tomcat-9/v9.0.17/bin/{{ package_name }}.tar.gz
      dest: /opt/{{ package_name }}.tar.gz   
  - name: "unzipping tar"
    unarchive:
      src: /opt/{{ package_name }}.tar.gz
      dest: /opt/
      remote_src: yes
  - name: "moving files to tomcat folder"
    command: mv /opt/{{ package_name }} /opt/tomcat
  - name: "changing owner to tomcat"
    file:
      path: /opt/tomcat
      owner: tomcat
      group: tomcat
      recurse: yes
  - name: "giving excutable permission to tomcat files"
    file:
      path: /opt/tomcat/bin/
      mode: 0755
      recurse: yes
  - name: "setting catalina file"
    copy:
      content: 'export CATALINA_HOME=/opt/tomcat'
      dest: ~/.bashrc
  - name: "refresh bashrc"
    shell: source ~/.bashrc
    args:
      executable: /bin/bash
  - name: "starting tomcat"
    shell: ./startup.sh
    args:
      chdir: /opt/tomcat/bin
  - name: "stoping tomcat"
    shell: ./shutdown.sh
    args:
      chdir: /opt/tomcat/bin
  - name: "changing owner for file"
    shell: chown -hR tomcat:tomcat /opt/tomcat/
  - name: "creating tomcat.server file"
    copy:
      src: copy/tomcat.service
      dest: /etc/systemd/system/
  - name: "reloading systemctl"
    systemd:
      name: tomcat
      daemon-reload: yes
      state: restarted
  - name: "starting tomcat"
    systemd:
      name: tomcat
      state: started
  - name: "configuring tomcat-user file"
    file:
      path: /opt/tomcat/conf/tomcat-users.xml
      state: absent
  - name: "updating tomcat-user file"
    copy:
      src: copy/tomcat-users.xml
      dest: /opt/tomcat/conf/
  - name: "modifing manager context file"
    file: 
      path: /opt/tomcat/webapps/manager/META-INF/context.xml
      state: absent
  - name: "updating manager context file"
    copy: 
      src: copy/manager/context.xml
      dest: /opt/tomcat/webapps/manager/META-INF/
  - name: "modifing host-manager context file"
    file: 
      path: /opt/tomcat/webapps/host-manager/META-INF/context.xml
      state: absent
  - name: "updating host-manager context file"
    copy: 
      src: copy/host-manager/context.xml
      dest: /opt/tomcat/webapps/host-manager/META-INF/ 
    notify:
    - restart tomcat
  - debug:
      msg: "deploying game of life"
  - name: "downloading game of life"
    get_url:
      url: https://github.com/QT-DevOps/DevOpsIssues/files/2130588/gameoflife.zip 
      dest: /opt/tomcat/webapps/
  - name: "unzipiing gameoflige"
    unarchive:
      src: /opt/tomcat/webapps/gameoflife.zip
      dest: /opt/tomcat/webapps/
      remote_src: yes
    notify:
    - restart tomcat 
