- name: Ensure expected distribution
  assert:
    that: ansible_os_family == "RedHat"

- name: Ensure expected variables
  assert:
    that:
      - upgrade_pulp_build is defined
      - upgrade_pulp_version is defined
      - upgrade_pulp_build in ['beta', 'nightly', 'stable']
    msg: |
      upgrade_pulp_build and upgrade_pulp_version must be defined.
      Also upgrade_pulp_build must be one of beta, nightly and stable.

- name: Nightly to_url
  set_fact:
    to_url: "testing/automation/{{ upgrade_pulp_version }}/stage/"
  when: upgrade_pulp_build == "nightly"

- name: Beta/Stable to_url
  set_fact:
    to_url: "{{ upgrade_pulp_build }}/{{ upgrade_pulp_version }}/"
  when: upgrade_pulp_build != "nightly"

- name: Update the repository baseurl
  lineinfile:
    dest: /etc/yum.repos.d/pulp.repo
    regexp: '^baseurl='
    line: 'baseurl=https://repos.fedorapeople.org/pulp/pulp/{{ to_url }}{% if ansible_distribution == "Fedora" %}fedora-{% endif %}$releasever/$basearch/'

- name: Stop services
  service: "name={{ item }} state=stopped"
  loop:
    - httpd
    - pulp_celerybeat
    - pulp_resource_manager
    - pulp_streamer
    - pulp_workers

- name: Clean all package cache
  shell: "{{ ansible_pkg_mgr }} clean all"

- name: Update packages
  shell: "{{ ansible_pkg_mgr }} -y update"

- name: Run pulp-manage-db
  shell: sudo -u apache pulp-manage-db

- name: Run daemon reload
  shell: "systemctl daemon-reload"
  when: ansible_distribution_major_version|int > 6

- name: Start services
  service: "name={{ item }} state=started"
  loop:
    - httpd
    - pulp_celerybeat
    - pulp_resource_manager
    - pulp_streamer
    - pulp_workers
