---
- name: Populate the server
  shell: >
    source "{{ ansible_user_dir }}/.venvs/pulp-migrate/bin/activate" &&
    pytest --junit-xml "{{ test_results_dir }}/populate.test.report.xml" --pyargs pulp_migrate.populate
  ignore_errors: yes
  # We would rather find out about errors from the xml report and not halt all execution
