---
- name: 'Setup Puppet 5 Repository'
  yum:
    name: https://yum.puppet.com/puppet5-release-el-{{ ansible_distribution_major_version }}.noarch.rpm
    disable_gpg_check: True
    state: present
  tags:
    - packages
