# rhel7 pulp 2.13.z restore
- name: Ensure expected variables
  assert:
    that:
      - remote_bkup_dir is defined
      - local_bkup_dir is defined
    msg: |
      Location of remote backup directory and local directory for backup to be copied to
      must be specified with varibales remote_bkup_dir and local_bkup_dir

- name: Install dependencies
  action: "{{ ansible_pkg_mgr }} name={{ item }} state=present"
  loop:
    - tar
    - bzip2
    - bzip2-libs

- name: Stop Pulp
  service: "name={{ item }} state=stopped"
  loop:
    - httpd
    - pulp_celerybeat
    - pulp_resource_manager
    - pulp_streamer
    - pulp_workers
    - qpidd
  notify: Start Pulp

- name: Make sure backup folder exists
  file: "path={{ remote_bkup_dir }} state=directory"

- name: Copy filesystem backups to remote
  copy:
    src: "{{ local_bkup_dir }}/{{ item.value.archive }}"
    dest: "{{ remote_bkup_dir }}"
  with_dict: "{{ files_to_restore }}"

- name: Unarchive filesystem backups
  command: "tar vxjf {{ remote_bkup_dir }}/{{ item.value.archive }} --overwrite"
  args:
    chdir: "/"
  with_dict: "{{ files_to_restore }}"

- name: Reset SELinux labels
  command: "restorecon -r {{ item.value.dest_dir }}"
  with_dict: " {{ files_to_restore }}"

- name: Drop pulp database
  command: "mongo pulp_database --eval 'db.dropDatabase()'"

# unarchive module fails probably because
# it relies on the using the "--diff" option which fails when
# unarchiving a directory full of files that don't yet exist
# See: https://github.com/ansible/ansible-modules-core/issues/2936#issuecomment-189579092
- name: Copy database backups to remote
  copy:
    src: "{{ local_bkup_dir }}/{{ db_to_restore.archive }}"
    dest: "{{ remote_bkup_dir }}"

- name: Unarchive database backups
  command: "tar vxjf {{ remote_bkup_dir }}/{{ db_to_restore.archive }}"
  args:
    chdir: "{{ remote_bkup_dir }}"

- name: Restore database from backup
  command: "mongorestore {{ remote_bkup_dir }}/{{ db_to_restore.dir }}"

- name: Run pulp-manage-db
  command: "sudo -u apache pulp-manage-db"
