# Example: GRUB_CMDLINE_LINUX="crashkernel=auto rd.lvm.lv=rhel/root quiet ..."
- name: Check existence of /boot
  shell: df -kh | grep -i "/boot"
  register: boot_check
  failed_when: boot_check.rc >=2

# For baremetal or KVMs that have /boot
- name: Enable FIPS for systems with /boot
  lineinfile:
    path: /etc/default/grub
    backrefs: true
    regexp: '^(GRUB_CMDLINE_LINUX=")(.*")'
    line: '\1fips=1 boot=UUID={{ (ansible_mounts | selectattr("mount", "equalto", "/boot") | list)[0]["uuid"] }} \2'
  become: true
  when: boot_check.rc == false

# For Openstack instances without /boot
- name: Enable FIPS for systems without /boot
  lineinfile:
    path: /etc/default/grub
    backrefs: true
    regexp: '^(GRUB_CMDLINE_LINUX=")(.*")'
    line: '\1fips=1 root=UUID={{ (ansible_mounts | selectattr("mount", "equalto", "/") | list)[0]["uuid"] }} \2'
  become: true
  when: boot_check.rc == true

- name: Check whether system was booted in EFI mode
  stat:
    path: /sys/firmware/efi
  register: result

- name: Make grub2 config in BIOS mode
  command: grub2-mkconfig -o /etc/grub2.cfg
  become: true
  when: result.stat.exists == false
  notify:
  - Restart host

- name: Make grub2 config in EFI mode
  command: grub2-mkconfig -o /etc/grub2-efi.cfg
  become: true
  when: result.stat.exists == true
  notify:
  - Restart host
