---
dependencies:
  - role: etc_hosts
  - role: foreman_server_repositories
    foreman_server_repositories_ostree: true
    foreman_server_repositories_katello: true
    foreman_server_repositories_foreman_client: true
  - role: ruby_scl
  - role: nodejs_scl
  - role: postgresql_scl
  - role: foreman_installer_devel_scenario
  - role: foreman_installer
    foreman_installer_scenario: katello-devel
    foreman_installer_additional_packages:
      - foreman-installer-katello
    foreman_installer_disable_system_checks: true
    foreman_installer_options_internal_use_only:
      - "--katello-devel-scl-ruby={{ ruby_scl_version }}"
      - "--katello-devel-admin-password {{ foreman_installer_admin_password }}"
  - role: customize_home
