---
- name: Stop services
  service:
    name: "{{ item }}"
    state: stopped
  loop: "{{ pulp_coverage_services }}"

- name: Clean up previous coverage data
  file:
    path: /srv/pulp_coverage
    state: absent

- name: Create Pulp coverage directory
  file:
    mode: 01777
    path: /srv/pulp_coverage
    state: directory
    group: apache
    owner: apache
    selevel: s0
    serole: object_r
    seuser: system_u
    setype: httpd_sys_rw_content_t

- name: Clone coverage repository
  git:
    repo: https://github.com/pulp/pulp.git
    dest: pulp
    depth: 1
    version: 2-master

- name: Install pip package
  action: "{{ ansible_pkg_mgr }} name=python-pip state=latest"

- name: Install coverage package
  command: pip install -U coverage

- name: Install the coverage hook
  command: ./coverage_hook install
  args:
    chdir: pulp/playpen/coverage

- name: Start services
  service:
    name: "{{ item }}"
    state: started
  loop: "{{ pulp_coverage_services }}"
