---
- name: Stop services
  service:
    name: "{{ item }}"
    state: stopped
  loop: "{{ pulp_coverage_services }}"

- name: Generate the coverage report
  command: >
      ./coverage_hook report
      {% if pulp_coverage_report_erase|bool %}--erase{% endif %}
      {% if pulp_coverage_report_html|bool %}--html{% endif %}
      {% if pulp_coverage_report_xml|bool %}--xml{% endif %}
      {{ pulp_coverage_report_dir }}
  args:
    chdir: pulp/playpen/coverage

- name: Start services
  service:
    name: "{{ item }}"
    state: started
  loop: "{{ pulp_coverage_services }}"
