---
- name: Uninstall the coverage hook
  command: ./coverage_hook uninstall
  args:
    chdir: pulp/playpen/coverage

- name: Remove coverage directory
  file:
    path: /srv/pulp_coverage
    state: absent

- name: Restart services
  service:
    name: "{{ item }}"
    state: restarted
  loop: "{{ pulp_coverage_services }}"
