---
- include_tasks: certs_generate.yml

- name: 'Run installer upgrade'
  include_role:
    name: foreman_installer
    tasks_from: upgrade
  vars:
    foreman_installer_scenario: foreman-proxy-content
    foreman_installer_disable_system_checks: True
    foreman_installer_options_internal_use_only:
      - --certs-update-all
      - --certs-regenerate=true
      - --certs-deploy=true
      - --certs-tar-file="{{ foreman_proxy_content_certs_tar }}"
